# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andy Ang J. L.
title: Data Scientist
email: andyangjunlong@outlook.sg
phone: (+65) 94749274
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: andyajl
linkedin_username: andyangjunlong
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I am an analytically minded data scientist with more than 9 years of experience collaborating with cross-functional team to solve real-world business problems using data-driven approaches.
  Bring significant practical experience in end-to-end predictive modeling, interpret large datasets, translate data into actionable business insights.
  <br />
  <br />
  <span style="color:#EBBD14">Skills:</span> *Machine Learning, Statistics, Data Visualisation, Data Wrangling, Descriptive Analysis, ETL* <br />
  <span style="color:#EBBD14">Soft Skills:</span> *Critical thinking, Research, Collaboration, Time management, Communication* <br />
  <span style="color:#EBBD14">Data and Analytics Tools/Languages:</span> *SAS, Python, R, SQL, Tableau, QlikSense, Cloudera Data Science Workbench* <br />
  <span style="color:#EBBD14">Hadoop Ecosystem:</span> *Hive, Impala, Sqoop, PySpark, Oozie, Hue*

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ministry of Defence (MINDEF)
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: <span style="color:#EBBD14">Data Scientist</span>
        caption: April 2022 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Deliver data science solutions to enhance MINDEF/SAF’s decision making in policy, operations and resource management.
      - layout: left
        title: United Overseas Bank (UOB)
        sub_title: <span style="color:#EBBD14">Vice President, Data Scientist</span>
        caption: November 2018 - April 2022
        description: | # this will include new lines to allow paragraphs
            - Project lead for the development and implementation of wealth propensity model which <span style="color:#EBBD14">increased conversion rates by 3.7 times</span> and <span style="color:#EBBD14">generated an incremental revenue of more than $13M.</span>
            - Project lead for the development and implementation of content recommender which <span style="color:#EBBD14">improved open rate by 2.6 times and click rate by 1.4 times.</span>
            - Project lead for the development and implementation of wealth propensity model for UOB Thailand which <span style="color:#EBBD14">increased conversion rates by 1.8 times.</span>
            - Actively communicated machine learning concepts and intuitions, ensure analysis and model outputs are understood and useable.
            - Designed experiments to monitor consistency of model performance and identify areas to improve.
            - Worked closely with customer segments team to understand the business, use data across multiple sources to generate insights, drive customer engagement, product usage and acquisition.
            - <span style="color:#EBBD14">Received CEO letter of performance recognition (2020).</span>
      - layout: left
        title: Prudential Assurance Company Singapore
        sub_title: <span style="color:#EBBD14">Data Scientist</span>
        caption: March 2018 - November 2018
        description: | # this will include new lines to allow paragraphs
            - Implemented customer segmentation engine that group customers into pre-defined microsegments.
            - Implemented next best offer engine for cross selling of insurance products.
            - Developed propensity to claim model to improve STP rate for underwriting.
            - Evaluated and improved on existing predictive models for E-claims project.
      - layout: left
        title: Development Bank of Singapore (DBS)
        sub_title: <span style="color:#EBBD14">Associate, Business Analyst</span>
        caption: August 2016 - March 2018
        description: | # this will include new lines to allow paragraphs
            - Developed wealth propensity model for identifying potential investors.
            - Worked closely with product teams on various campaign initiatives, using  data to generate insights, drive product usage and acquisition.
            - Developed campaign tracking methodology to evaluate the effectiveness of different targeting criteria for each campaign.
            - Consolidated and prepared data into a cohesive and comprehensible form.
            - Performed descriptive analysis and generated periodic statistical reports for management decision-making.
      - layout: left
        title: Singapore Institute of Manufacturing Technology (SIMTech | A*STAR)
        sub_title: <span style="color:#EBBD14">Specialist</span>
        caption: October 2013 - July 2016
        description: | # this will include new lines to allow paragraphs
            - Provide text-mining solutions for Antuit-SIMTech Supply Chain Analytics Lab.
            - Research in data mining for supply chain and manufacturing systems.
  
  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - National University of Singapore (NUS) <span style="color:#EBBD14">Master of Technology in Knowledge Engineering</span> (Jan 2015 – Jun 2017)
      - National University of Singapore (NUS) <span style="color:#EBBD14">Bachelor of Science in Statistics</span> (Aug 2010 – Jun 2013)
  
  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Deep Learning Specialisation
        - <a href="https://coursera.org/share/8b9f4402dea8e49432fee4065d698c1e">Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization</a>
        - <a href="https://coursera.org/share/f2a312bc381e3394658742a088d94389">Structuring Machine Learning Projects</a>
        - <a href="https://coursera.org/share/5eca10a25c5011313069af8733e4f93c">Neural Networks and Deep Learning</a>
      - SAS
        - Customised SAS Programming
        - SAS Macros
        - SAS SQL   
      
  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - <a href="https://ieeexplore.ieee.org/abstract/document/7385717"><span style="color:#EBBD14">Ang, J.L.</span>, Ong, B.Y. and Tan, P.S., 2015, December. An application of text mining to understand the productivity challenges in Singapore. In 2015 IEEE International Conference on Industrial Engineering and Engineering Management (IEEM) (pp. 595-600). IEEE. <span style="color:#EBBD14">(Nominated Best Paper Award)</span></a>
      - <a href="https://ieeexplore.ieee.org/abstract/document/7841042">Goh, G.S., <span style="color:#EBBD14">Ang, A.J.</span> and Zhang, A.N., 2016, December. Optimizing performance of sentiment analysis through design of experiments. In 2016 IEEE International Conference on Big Data (Big Data) (pp. 3737-3742). IEEE.</a>
      - <a href="https://ieeexplore.ieee.org/abstract/document/7058722">Bhullar, A.S., Gan, C.W., <span style="color:#EBBD14">Ang, A.J.</span>, Ma, B., Lim, R.Y. and Toh, M.H., 2014, December. Operational excellence frameworks—Case studies and applicability to SMEs in Singapore. In 2014 IEEE International Conference on Industrial Engineering and Engineering Management (pp. 667-671). IEEE.</a>
      
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
