# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andy Ang J. L.
title: Data Analyst/Scientist
email: andyangjunlong@outlook.sg
phone: (+65) 9474 9274
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: andyajl
linkedin_username: andyangjunlong
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I am an experienced data analyst/scientist with over 10 years of expertise in leveraging data-driven methodologies to tackle real-world business challenges. 
  My strong analytical mindset and collaborative approach enable me to work effectively with cross-functional teams. I have a proven track record in end-to-end predictive modeling, interpreting extensive datasets and transforming data into actionable insights that drive business success.
  <br />
  <br />
  <span style="color:#EBBD14">Technical Skills:</span> *Statistical Analysis, Machine Learning, Statistics, Data Visualisation, Data Wrangling, Data Mining, Descriptive Analysis, ETL, Experimental Design and A/B Testing, AWS Certified Cloud Practitioner* <br />
  <span style="color:#EBBD14">Soft Skills:</span> *Critical thinking, Research, Collaboration, Time management, Communication* <br />
  <span style="color:#EBBD14">Data and Analytics Tools/Languages:</span> *SAS, Python, R, SQL, Tableau, Qlik Sense, Cloudera Data Science Workbench* <br />
  <span style="color:#EBBD14">Data Science Frameworks:</span> *Scikit-Learn, Tensorflow, Keras, XGBoost, NLTK* <br />
  <span style="color:#EBBD14">Hadoop Ecosystem:</span> *Hive, Impala, Sqoop, PySpark, Oozie, Hue*

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: United Overseas Bank (UOB)
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Finance Data Analytics<br /> <span style="color:#EBBD14">Vice President</span>
        caption: August 2023 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Establish a knowledge base and develop operating guidelines for selecting optimal enterprise tools, streamlining dashboarding, report extraction, and model building within UOB’s infrastructure.
            - Design and develop sustainable data assets by integrating multiple data sources to enhance ad-hoc analysis and reporting, accelerating turnaround time and minimizing data duplication.
            -	Develop and maintain guidelines for script development and dataset management, ensuring consistent and reliable data processes within the team.
            -	Lead a team to spearhead data analysis initiatives, ensuring successful project execution and delivering impactful results.
      - layout: left
        title: Ministry of Defence (MINDEF)
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Data Science Department<br /> <span style="color:#EBBD14">Data Scientist</span>
        caption: April 2022 - August 2023
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Delivered data science solutions to enhance MINDEF/SAF's decision-making in policy, operations, and resource management.
            - Led development and implementation of data science solutions, including NLP, anomaly detection and policy query engine, to drive actionable insights and solve complex business challenges.
            - Led a delegation of four to Machine Learning Week 2022, acquiring valuable industry insights into the practical applications of predictive analytics.
            -	Conducted hands-on machine learning workshop for over 300 participants at IGNITE Innovation Symposium 2022.
      - layout: left
        title: United Overseas Bank (UOB)
        sub_title: Customer Franchise & Business Analytics<br /> <span style="color:#EBBD14">Data Scientist, Vice President</span>
        caption: November 2018 - April 2022
        description: | # this will include new lines to allow paragraphs
            - <span style="color:#EBBD14">Received CEO letter of performance recognition (2020).</span>
            - Project lead for the <span style="color:#EBBD14">development and implementation of wealth propensity model which increased conversion rates by 3.7 times</span> and <span style="color:#EBBD14">generated an incremental revenue of more than $13M.</span>
            - Project lead for the <span style="color:#EBBD14">development and implementation of content recommender which improved open rate by 2.6 times and click rate by 1.4 times.</span>
            - Project lead for the <span style="color:#EBBD14">development and implementation of wealth propensity model for UOB Thailand which increased conversion rates by 1.8 times.</span>
            - <a href="https://www.mas.gov.sg/-/media/MAS-Media-Library/news/media-releases/2022/Veritas-Document-3B---FEAT-Ethics-and-Accountability-Principles-Assessment-Methodology.pdf">UOB’s subject matter expert on customer marketing use case for the development of the Ethics and Accountability Assessment Methodology (MAS-led Veritas Consortium).</a>
            - <span style="color:#EBBD14">Designed, developed, maintained various interactive dashboards</span> using Qlik Sense for business reporting and generating actionable insights toward desired financial outcomes.  
            - Designed experiments to monitor consistency of model performance and identify areas to improve.
            - Worked closely with customer segments team to understand the business, use data across multiple sources to generate insights, drive customer engagement, product usage and acquisition.
            - Provided guidance and technical support for multiple interns.
      - layout: left
        title: Prudential Assurance Company Singapore
        sub_title: Data & Analytics IT<br /> <span style="color:#EBBD14">Data Scientist, Manager</span>
        caption: March 2018 - November 2018
        description: | # this will include new lines to allow paragraphs
            - Implemented <span style="color:#EBBD14">customer segmentation engine</span> that group customers into pre-defined microsegments.
            - Implemented <span style="color:#EBBD14">next best offer engine</span> for cross selling of insurance products.
            - Developed <span style="color:#EBBD14">propensity to claim model</span> to improve STP rate for underwriting.
            - Evaluated and improved on existing predictive models for E-claims project.
      - layout: left
        title: Development Bank of Singapore (DBS)
        sub_title: Financial Planning Group<br /> <span style="color:#EBBD14">Business Analyst, Associate</span>
        caption: August 2016 - March 2018
        description: | # this will include new lines to allow paragraphs
            - Developed <span style="color:#EBBD14">wealth propensity model</span> for identifying potential investors.
            - Worked closely with product teams on various campaign initiatives, using  data to generate insights, drive product usage and acquisition.
            - Developed campaign tracking methodology to evaluate the effectiveness of different targeting criteria for each campaign.
            - Consolidated and prepared data into a cohesive and comprehensible form.
            - Performed descriptive analysis and generated periodic statistical reports for management decision-making.
      - layout: left
        title: Singapore Institute of Manufacturing Technology (SIMTech | A*STAR)
        sub_title: Planning and Operations Management Group<br /> <span style="color:#EBBD14">Specialist</span>
        caption: October 2013 - July 2016
        description: | # this will include new lines to allow paragraphs
            - Provide <span style="color:#EBBD14">text-mining solutions</span> for Antuit-SIMTech Supply Chain Analytics Lab.
            - Research in data mining for supply chain and manufacturing systems.
  
  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - National University of Singapore (NUS) <br /> <span style="color:#EBBD14">Master of Technology in Knowledge Engineering</span> *Jan 2015 – Jun 2017* (4.39/5)
      - National University of Singapore (NUS) <br /> <span style="color:#EBBD14">Bachelor of Science in Statistics</span> *Aug 2010 – Jun 2013* (3.76/5)
  
  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - <a href="https://www.credly.com/badges/0d8a73c9-a9e2-4c8c-ab0c-0109fbba31d9">AWS Certified Cloud Practitioner (May 2023)</a>
      - <a href="https://www.coursera.org/account/accomplishments/specialization/8C2DZQ6XDF37">Deep Learning Specialisation (Aug 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/verify/MKFLX4AXZRMT">Sequence Models (Aug 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/4A9LQQRBN9H3">Convolution Neural Networks (Jul 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/ELZP6GHJFZ6X">Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization (Jul 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/9CUTMQA6YERM">Structuring Machine Learning Projects (Jul 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/E6R3YFWH48GV">Neural Networks and Deep Learning (Jun 2022)</a>
      - Machine Learning Engineering for Production (MLOps) Specialisation
        - <a href="https://www.coursera.org/account/accomplishments/certificate/QS3UAXC4LJHM">Introduction to Machine Learning in Production (Aug 2022)</a>
      - SAS (Aug 2016)
        - Customised SAS Programming
        - SAS Macros
        - SAS SQL   
      - <a href="https://www.coursera.org/account/accomplishments/specialization/certificate/EXQDU4PB8FY5">Django for Everybody Specialisation (Dec 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/DVGH6BYDWKJS">Using JavaScript, JQuery, and JSON in Django (Dec 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/MTZEW8RLEZUK">Django Features and Libraries (Nov 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/FTFRT699DCB2">Web Applications Technologies and Django (Oct 2022)</a>
        - <a href="https://www.coursera.org/account/accomplishments/certificate/P8ENFCV3RPLN">Building Web Applications in Django (Oct 2022)</a>
        

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - <a href="https://ieeexplore.ieee.org/abstract/document/7385717"><span style="color:#EBBD14">Ang, J.L.</span>, Ong, B.Y. and Tan, P.S., 2015, December. An application of text mining to understand the productivity challenges in Singapore. In 2015 IEEE International Conference on Industrial Engineering and Engineering Management (IEEM) (pp. 595-600). IEEE. <span style="color:#EBBD14">(Nominated Best Paper Award)</span></a>
      - <a href="https://ieeexplore.ieee.org/abstract/document/7841042">Goh, G.S., <span style="color:#EBBD14">Ang, A.J.</span> and Zhang, A.N., 2016, December. Optimizing performance of sentiment analysis through design of experiments. In 2016 IEEE International Conference on Big Data (Big Data) (pp. 3737-3742). IEEE.</a>
      - <a href="https://ieeexplore.ieee.org/abstract/document/7058722">Bhullar, A.S., Gan, C.W., <span style="color:#EBBD14">Ang, A.J.</span>, Ma, B., Lim, R.Y. and Toh, M.H., 2014, December. Operational excellence frameworks—Case studies and applicability to SMEs in Singapore. In 2014 IEEE International Conference on Industrial Engineering and Engineering Management (pp. 667-671). IEEE.</a>
      
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
